services:
  aeproject_node:
    image: aeternity/aeternity:${NODE_TAG:-latest}-bundle
    hostname: node
    # TODO: remove after releasing https://github.com/aeternity/aeternity/pull/4292
    healthcheck:
      interval: 2s
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
      AE__SYSTEM__CUSTOM_PREFUNDED_ACCS_FILE: "/home/aeternity/node/data/aecore/.genesis/accounts_test.json"
    volumes:
      - "./docker/aeternity.yaml:/home/aeternity/aeternity.yaml"
      - "./docker/accounts.json:/home/aeternity/node/data/aecore/.genesis/accounts_test.json"

  aeproject_compiler:
    image: aeternity/aesophia_http:${COMPILER_TAG:-latest}
    hostname: compiler
    # TODO: remove after releasing https://github.com/aeternity/aesophia_http/pull/133
    healthcheck:
      interval: 2s
    ports:
      - "3080:3080"

  aeproject_proxy:
    image: nginx:latest
    hostname: proxy
    ports:
      - "3001:3001"
    volumes:
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - aeproject_compiler
      - aeproject_node
